### ISSUE TITLE
Trigger with button possible

### ISSUE THREAD

**Issue by fourroses666** [bossloper/CacheClean#3]
Installed it on a site to test it. 
I use WebpConverter and have a cached image which I would like to get refreshed.
Is there a way to trigger the cleanup on command?

**Comment by bossloper** [comment]
It was not really designed for that. Just a lazy catch-all clean-up to stop disk space running away over a long period of time.
Maybe you could copy the code to a snippet and run it manually with no random factor?

**Comment by fourroses666** [comment]
Ah I understand. Snippet would be the way then.

Having a second thought about it because phpthumb generates images with 3 random numbers added to the filename and that would be not that good for SEO if an image is indexed and disappears. (For clients who really need SEO)

**Comment by bossloper** [comment]
Yes, I would only use it for long-term 'big picture' clean-up. Maybe images over a year old or more even. I have a website ticking away for a 4-5 years with client managers and lots of page changes. The cache folder ended up filling the quota!

**Comment by fourroses666** [comment]
Thats a perfect plugin for that case indeed. 😬
